package link.locutus.discord.db.guild;

public enum GuildSettingSubgroup {
    NONE,

    DEFENSIVE_WARS,
    OFFENSIVE_WARS,
    BEIGE_VIOLATIONS,
    ENEMY_ALERT,
    EXODUS_ALERT,
    ALLIANCE_GROUND_ALERT,
    MEMBER_WITHDRAWAL,
    BANK_LIMITS,
    GRANT_TEMPLATE_LIMIT,
    DEPOSIT_DISPLAY,
    GRANT_REQUESTS,
    TAX_SELF_ASSIGN,
    TAX_AUTO_ASSIGN,
    AUTO_AUDITS,
    MANUAL_AUDITS,
    SELF_ROLE,
    ROLE_SERVER_SYNC,
    ALLIANCE_ROLE,

    NATION_CREATION,
    ALLIANCE_APPLICATION
}
