package link.locutus.discord.util.task.roles;

public enum AutoRoleIssueType {
    NOT_REGISTERED,
    MISSING_REGISTERED_ROLE_MAPPING,
    MISSING_REGISTERED_ROLE,
    AUTO_NICKNAME_DISABLED,
    PLANNING_FAILED,
    CREATE_ROLE_FAILED,
    ADD_ROLE_FAILED,
    REMOVE_ROLE_FAILED,
    RENAME_ROLE_FAILED,
    SET_NICKNAME_FAILED,
    CLEAR_NICKNAME_FAILED,
    ROLE_ALREADY_PRESENT,
    ROLE_NOT_PRESENT,
    ROLE_ALREADY_NAMED,
    NICKNAME_ALREADY_SET,
    NICKNAME_NOT_PRESENT
}
