@import java.util.List
@import link.locutus.discord.commands.manager.v2.binding.WebStore
@import link.locutus.discord.commands.manager.v2.impl.pw.binding.NationAttribute

@param WebStore ws
@param List<NationAttribute> metricsDouble
@param List<NationAttribute> metricsInteger
@param List<NationAttribute> metricsBoolean
@param List<NationAttribute> metricsString
<form>

</form>
<script>
// TODO on submit, collect all the values
</script>