package link.locutus.discord.db.conflict;

import it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap;

import java.util.Map;

public class LegacyAllianceNames {
    public static Map<String, Integer> get() {
        Map<String, Integer> legacyIds = new Object2IntOpenHashMap<>();
        legacyIds.put("Arrgh!", 913);
        legacyIds.put("The Hive", 8819);
        legacyIds.put("Zodiac", 4145);
        legacyIds.put("Resplendent Inc.", 2844);
        legacyIds.put("Phoenix", 1809);
        legacyIds.put("Hogwarts", 9110);
        legacyIds.put("Global United Nations", 107);
        legacyIds.put("Blue Moon", 3003);
        legacyIds.put("Animal Empire", 4158);
        legacyIds.put("Cobalt", 770);
        legacyIds.put("IKEA", 8777);
        legacyIds.put("Ignis Aternum", 11713);
        legacyIds.put("IronFront", 5462);
        legacyIds.put("InGen", 1634);
        legacyIds.put("Dutch East India Company", 9997);
        legacyIds.put("The Chola", 2047);
        legacyIds.put("The Kings Parliament", 1804);
        legacyIds.put("Ex Machina", 7414);
        legacyIds.put("DawnGuard", 11513);
        legacyIds.put("Dawn Rising", 8520);
        legacyIds.put("Clover Kingdom", 7094);
        legacyIds.put("New Pacific Order", 2082);
        legacyIds.put("Divine Phoenix Empire", 8173);
        legacyIds.put("Divine Phoenix", 8173);
        legacyIds.put("Aeterna", 11841);
        legacyIds.put("The Empire of the Moonlit Sakura", 4623);
        legacyIds.put("The Federation", 4638);
        legacyIds.put("The Manhattan Cartel", 5851);
        legacyIds.put("The North Western South Region of the Far East", 6703);
        legacyIds.put("The Paladin", 11568);
        legacyIds.put("The Rohirrim", 7540);
        legacyIds.put("The Ronin Empire", 7376);
        legacyIds.put("The Three Swords", 10374);
        legacyIds.put("The United Armies", 5326);
        legacyIds.put("ThunderStruck", 7635);
        legacyIds.put("Titanio", 7642);
        legacyIds.put("United Commerce Republic", 8651);
        legacyIds.put("VooDoo", 8804);
        legacyIds.put("Waffle House", 10936);
        legacyIds.put("Swords of Sanghelios", 8173);
        legacyIds.put("Terran Federation", 9110);
        legacyIds.put("The Circus", 9521);
        legacyIds.put("The Coal Mines (2nd)", 7094);
        legacyIds.put("The Coven", 9573);
        legacyIds.put("The Elites", 8429);
        legacyIds.put("Order of the White Rose", 2510);
        legacyIds.put("Polaris", 2358);
        legacyIds.put("Prima Victoria", 7570);
        legacyIds.put("Roman Empire", 9600);
        legacyIds.put("Serene Repubblica Fiorentina", 9927);
        legacyIds.put("Serene Wei", 1742);
        legacyIds.put("Roz Wei", 1742);
        legacyIds.put("Terminal Jest", 7620);
        legacyIds.put("Nuclear Knights",1634);
        legacyIds.put("Animation Domination", 4597);
        legacyIds.put("Cornerstone", 1037);
        legacyIds.put("Seven Kingdoms", 615);
        legacyIds.put("Nordic Sea Raiders", 4341);
        legacyIds.put("Soldiers of Liberty", 6215);
        legacyIds.put("Spartan Brotherhood", 6161);
        legacyIds.put("Spartan Republic", 7380);
        legacyIds.put("Sunray 1-1", 9651);
        legacyIds.put("Sunray Victoria", 10466);
        legacyIds.put("Atlas Technological Cooperative", 7306);
        legacyIds.put("Ghost Division", 9588);
        legacyIds.put("Children of the Light", 7452);
        legacyIds.put("iriririr", 12438);
        legacyIds.put("United Nations 2", 12359);
        legacyIds.put("insinsaneane", 12450);
        legacyIds.put("Noble Wei", 12382);
        legacyIds.put("Convent of Atom",7531);
        legacyIds.put("The Ampersand",5722);
        legacyIds.put("Brotherhood of the Clouds",7703);
        legacyIds.put("Bank Robbers",7923);
        legacyIds.put("The Outhouse",7990);
        legacyIds.put("Not Rohans Bank",8014);
        legacyIds.put("Democracy",8060);
        legacyIds.put("Prusso Roman Imperial Union",7920);
        legacyIds.put("Avalanche",8150);
        legacyIds.put("Sanctuary",8368);
        legacyIds.put("Union of Soviet Socialist Republics",8531);
        legacyIds.put("Ad Astra",7719);
        legacyIds.put("Otaku Shougaku",8594);
        legacyIds.put("Wizards",8624);
        legacyIds.put("MDC",8615);
        legacyIds.put("Christmas",8614);
        legacyIds.put("MySpacebarIsBroken",8678);
        legacyIds.put("Lords of Wumbology",8703);
        legacyIds.put("Paragon",8502);
        legacyIds.put("Shuba2M",8909);
        legacyIds.put("Shuba69M",8929);
        legacyIds.put("Mensa HQ",8930);
        legacyIds.put("Shuba99M",8955);
        legacyIds.put("Not A Scam",8984);
        legacyIds.put("The Dead Rabbits",7540);
        legacyIds.put("The Vatican",9321);
        legacyIds.put("High Temple",9341);
        legacyIds.put("Shuba666M",9385);
        legacyIds.put("Crimson Dragons",9406);
        legacyIds.put("Apollo",9427);
        legacyIds.put("Nibelheim",9580);
        legacyIds.put("Starfleet",9850);
        legacyIds.put("OTSN",9883);
        legacyIds.put("The Knights Of The Round Table",9830);
        legacyIds.put("Wayne Enterprises",9931);
        legacyIds.put("LegoLand",9961);
        legacyIds.put("Wayne Enterprises Inc",9971);
        legacyIds.put("Paradise",9986);
        legacyIds.put("The Afterlyfe",10060);
        legacyIds.put("Esquire Templar",10070);
        legacyIds.put("The Naughty Step",10074);
        legacyIds.put("The Cove",10104);
        legacyIds.put("Pacific Polar",10248);
        legacyIds.put("Stigma",10326);
        legacyIds.put("Sparkle Party People",10329);
        legacyIds.put("Age of Darkness",10100);
        legacyIds.put("Lunacy",9278);
        legacyIds.put("The Entente",10396);
        legacyIds.put("Crawling Crawfish Conundrum",10398);
        legacyIds.put("Western Republic",10408);
        legacyIds.put("General Patton",10411);
        legacyIds.put("Crab Creation Contraption",10416);
        legacyIds.put("The Bugs palace",10414);
        legacyIds.put("Aggravated Conch Assault",10425);
        legacyIds.put("Castle Wall",10436);
        legacyIds.put("Mukbang Lobster ASMR",10440);
        legacyIds.put("House of the Dragon",10445);
        legacyIds.put("lobster emoji",10447);
        legacyIds.put("LobsterGEDDON",10449);
        legacyIds.put("ARMENIA FOREVER",10452);
        legacyIds.put("Stigma 1",10450);
        legacyIds.put("General Custer",10454);
        legacyIds.put("Scyllarides Saloon",10464);
        legacyIds.put("Camelot Squires",10468);
        legacyIds.put("bruh momento",10467);
        legacyIds.put("Limp Lobster",10474);
        legacyIds.put("OSNAP",10472);
        legacyIds.put("AAAAAAAAA",10486);
        legacyIds.put("Alpha Lobster",10485);
        legacyIds.put("Shuba73M",10489);
        legacyIds.put("Borgs Assisted Loot Liberation Service",10504);
        legacyIds.put("Cornhub",10521);
        legacyIds.put("xXxJaredLetoFanxXx",10529);
        legacyIds.put("Anti-Horridism Obocchama Kun Fan Club",10540);
        legacyIds.put("Iraq Lobster",10552);
        legacyIds.put("Mole Rats",10574);
        legacyIds.put("God I Love Frogs",10573);
        legacyIds.put("A-HOK Fan Club Fan Club",10583);
        legacyIds.put("MyKeyboardIsBroken",10683);
        legacyIds.put("Show Me The Money",10694);
        legacyIds.put("Banana Stand London Branch",10709);
        legacyIds.put("Sparkle of the Night",10712);
        legacyIds.put("Cru Whole Hole",10716);
        legacyIds.put("Arrghs offshore",10717);
        legacyIds.put("Banana Stand New York",10720);
        legacyIds.put("Anything",10739);
        legacyIds.put("Banana Stand Los Angeles",10733);
        legacyIds.put("Wayne Foundation",10746);
        legacyIds.put("Banana Stand On The Run",10747);
        legacyIds.put("Master Basters",10759);
        legacyIds.put("Turkey land",10757);
        legacyIds.put("Theres No Place Like Home",10764);
        legacyIds.put("Drake - Hotline Bling",8520);
        legacyIds.put("Yer A Wizard Harry",10783);
        legacyIds.put("A Truth Universally Acknowledged",10805);
        legacyIds.put("An Offer He Cant Refuse",10815);
        legacyIds.put("HAHA England lost to France",10834);
        legacyIds.put("Banco dei Medici",8520);
        legacyIds.put("The Bank of Orbis",10092);
        legacyIds.put("May The Force Be With You",10839);
        legacyIds.put("Shaken Not Stirred",10845);
        legacyIds.put("Shaken Not Stired",10848);
        legacyIds.put("ET Phone Home",10854);
        legacyIds.put("Cock of destiny",10855);
        legacyIds.put("Yo Adrian",10868);
        legacyIds.put("Autocephalous Patriarchate of the Free",10869);
        legacyIds.put("Mama Always Said",10878);
        legacyIds.put("offshoreassss",10887);
        legacyIds.put("Youre Tacky and I Hate You",10905);
        legacyIds.put("O Captain My Captain",10912);
        legacyIds.put("HIDUDE GIB TIERING REPORT",10917);
        legacyIds.put("Bank of The Holy Grail",10925);
        legacyIds.put("Shuba45M",10933);
        legacyIds.put("The IX Legion",10934);
        legacyIds.put("Sparkle Forever",10946);
        legacyIds.put("BOSNIA MODE",10949);
        legacyIds.put("Jotunheimr",8429);
        legacyIds.put("Fallen Monarchy",10988);
        legacyIds.put("Gunga Ginga",11005);
        legacyIds.put("Grand Union of Nations",11018);
        legacyIds.put("Calamity",11019);
        legacyIds.put("borgborgborgborgborgborgborg",11023);
        legacyIds.put("Fargos",11027);
        legacyIds.put("Event Horizon",11039);
        legacyIds.put("CATA_IS_SO_COOL",11036);
        legacyIds.put("Pasta Factory",11042);
        legacyIds.put("MERDE",11059);
        legacyIds.put("The Black League",11066);
        legacyIds.put("United Nations Space Command",10995);
        legacyIds.put("Loopsnake alliance",11064);
        legacyIds.put("Old Praxis",11075);
        legacyIds.put("DecaDeezKnuttz",11077);
        legacyIds.put("Eurovision 2023 incoming",11090);
        legacyIds.put("Animal Pharm",11165);
        legacyIds.put("The Imperial Vault",11209);
        legacyIds.put("The House of Bugs",11288);
        legacyIds.put("Midnight Blues",11304);
        legacyIds.put("Mace & Chain",11312);
        legacyIds.put("Skull & Bones",11008);
        legacyIds.put("Swiss Account",11350);
        legacyIds.put("No offshore here",11353);
        legacyIds.put("Dunce Cap Supreme",11359);
        legacyIds.put("Aunt Jemima",11360);
        legacyIds.put("Fortuna sucks",11372);
        legacyIds.put("Home Hero",11375);
        legacyIds.put("Pharm Animal",11368);
        legacyIds.put("The Children of Yakub",11370);
        legacyIds.put("Shuba65M",11371);
        legacyIds.put("Tower of London",11376);
        legacyIds.put("Tintagel Castle",11384);
        legacyIds.put("Killer Tomatoes",11386);
        legacyIds.put("Nessa Barrett",11391);
        legacyIds.put("Legion of Dusk",11390);
        legacyIds.put("The Semimortals",11394);
        legacyIds.put("State of Orbis",11401);
        legacyIds.put("King Tiger",11398);
        legacyIds.put("Toilet Worshipping Lunatics",11403);
        legacyIds.put("The Peaceful Warmongers",11405);
        legacyIds.put("North Mexico",11407);
        legacyIds.put("Ketamine Therapy",11406);
        legacyIds.put("Kiwi Taxidermy",11420);
        legacyIds.put("Kazakhstani Tramway",11435);
        legacyIds.put("Prenadores de Burras Profesionales",11441);
        legacyIds.put("Kidney Transplant",11444);
        legacyIds.put("Shuba63m",11450);
        legacyIds.put("Knockoff Tetragrammatons",11457);
        legacyIds.put("Castillo de Coca",11454);
        legacyIds.put("Kangaroo Testicles",11473);
        legacyIds.put("New Church Republic",11494);
        legacyIds.put("Kleptomaniac Tunisians",11493);
        legacyIds.put("Shuba777M",11510);
        legacyIds.put("Kitten Toes",11514);
        legacyIds.put("Atlas Three",11515);
        legacyIds.put("Kaleidoscope Technology",11525);
        legacyIds.put("Koala Tornado",11531);
        legacyIds.put("Skylines",11533);
        legacyIds.put("Palo Mayombe",11604);
        legacyIds.put("Mouseleys Superfan Fun Cheese Corner 5",11619);
        legacyIds.put("General Area of Two Ostritches",11643);
        legacyIds.put("The Persian Empire",10671);
        legacyIds.put("Bakerstreet",11699);
        legacyIds.put("The Radiant Syndication",11719);
        legacyIds.put("Make More Monitors",11714);
        legacyIds.put("Quack",11718);
        legacyIds.put("Panama City Beach",11710);
        legacyIds.put("Shadowhunters",11715);
        legacyIds.put("Storm",11721);
        legacyIds.put("Three Inch Surprise",11730);
        legacyIds.put("Greywater Watch",11731);
        legacyIds.put("Port St Lucie",11740);
        legacyIds.put("The Orphanage",11746);
        legacyIds.put("Halo Revived",11751);
        legacyIds.put("Saint Augustine",11753);
        legacyIds.put("Orange Brotherhood",11764);
        legacyIds.put("Demon Slayer",11765);
        legacyIds.put("The Hippo Horde",11763);
        legacyIds.put("Yeehaw Junction",11769);
        legacyIds.put("House Weeb",11772);
        legacyIds.put("Ockey Multi Mass Production Facility 7",11779);
        legacyIds.put("TCM Extension",11797);
        legacyIds.put("Bohemian Grove",11811);
        legacyIds.put("House Stark Crypto Wallet",11805);
        legacyIds.put("Two Egg",11817);
        legacyIds.put("Elfers",11830);
        legacyIds.put("Gamblers Anonymous",11862);
        legacyIds.put("Humza Useless",11876);
        legacyIds.put("The Merry Men",11900);
        legacyIds.put("Jacobite Rebellion",11899);
        legacyIds.put("The Media",11912);
        legacyIds.put("World of Farce",11952);
        legacyIds.put("Lyra",12022);
        legacyIds.put("Free Alrea",12029);
        legacyIds.put("Black Banana",12031);
        legacyIds.put("Cassiopeia",12034);
        legacyIds.put("Basil Land",12036);
        legacyIds.put("Better eclipse",12037);
        legacyIds.put("Planet express",12043);
        legacyIds.put("Seven WHO",12047);
        legacyIds.put("Aquila",12057);
        legacyIds.put("Rum Raiders",12062);
        legacyIds.put("Free Alrea 3",12067);
        legacyIds.put("Zapp spammigan",12068);
        legacyIds.put("Eridanus",12064);
        legacyIds.put("Neighborhood watch alliance",12066);
        legacyIds.put("House Apathy",12069);
        legacyIds.put("Free Alrea 4",12076);
        legacyIds.put("Taurus",12084);
        legacyIds.put("Vela",12090);
        legacyIds.put("Chavez Nuestro que Estas en los Cielos",12102);
        legacyIds.put("Cygnus",12134);
        legacyIds.put("Thin Skin Singularity",12190);
        legacyIds.put("Red Wine on THT",12261);
        legacyIds.put("Cute Cats Cuddling in a Cayak",12290);
        legacyIds.put("Narutos",12318);
        legacyIds.put("insane",12344);
        legacyIds.put("enasni",12362);
        legacyIds.put("Tax Scheme",12364);
        legacyIds.put("aneins",12369);
        legacyIds.put("aneane",12380);
        legacyIds.put("insane transposed",12421);
        legacyIds.put("anti insane",12429);
        legacyIds.put("Biker Haven", 11389);
        legacyIds.put("Hegemoney", 11709);
        return legacyIds;
    }
}
