# If the bot is running on the test server (default: false)
test: false
# The discord token of the bot (required)
# Found on the bot section of the Discord Developer Portal
bot-token: "OTg0NjAzMzkyNzY2Nzg3NjQ0.G4f72R._OXk8CrF_u3Hft7g059C2zvpfAUoz5pGAtGcho"
# The discord client secret of the bot (required)
# Found on the OAuth2 section of the Discord Developer Portal
client-secret: "C2V1O9uB7MfE8jEWb6yAFLT0YnbEV1qa"
# The guild id of the management server for this bot (you should be owner here)
# See: https://support.discord.com/hc/en-us/articles/206346498
root-server: 987054820902973600
# The guild id of the root coalition server (e.g. for spheres)
# Defaults to the root server server
root-coalition-server: 0
# The guild id to post the forum feed in
# Set to 0 to disable (default 0)
forum-feed-server: 0
# Your P&W username (optional)
username: "stranierisimone24@gmail.com"
# Your P&W password (optional)
password: "trismoka5610"
# Your api key (generated if username/password is set)
api-key-primary: "8480c8d031ce15"
# A list of api keys the bot can use for requests (optional)
# See: `$validateApiKeys`
api-key-pool: []
# The discord id of the bot (generated)
# Found in the General Information section of the Discord Developer Portal
application-id: 984603392766787644
# The discord user id of the admin user. (generated)
admin-user-id: 776336800851165224
# The nation id of the admin. (generated)
nation-id: 255385

enabled-components:
  # If the discord bot is enabled at all
  #  - Other components require the discord bot to be enabled
  discord-bot: true
  # If message commands e.g. `!who` is enabled
  message-commands: true
  # If slash `/` commands are enabled (WIP)
  slash-commands: false
  # If the web interface is enabled
  web: false
  # Should databases be initialized on startup
  # false = they are initialized as needed (I havent done much optimization here, so thats probably shortly after startup anyway, lol)
  create-databases-on-startup: false
  # Should any repeating tasks be enabled
  #  - See the task section to disable/adjust individual tasks
  repeating-tasks: true
  # If P&W events should be enabled
  events: true
  # Game of tag
  tag: false

# How often in seconds a task is run (set to 0 to disable)
tasks:
  turn-tasks:
    vm-nation-updater: true
    guild-alliance-tasks: true
    guild-nation-tasks: true
    alliance-metrics: true
    # TODO: Not finished
    map-full-alert: true
    # Update spy slots on turn change
    spy-slots: true
    # Update nation policy on turn change
    policy: true
    # Update nation projects on turn change
    project: true
    # If bank records should be fetched each turn (default: false)
    #  - If disabled, records will be fetched on demand
    bank-records: false
    # Update nation cities on turn change (default: true)
    #  - If disabled, records will be fetched on demand
    cities: false
  trade-tasks:
    # Fetches trades (default: 15 minutes)
    completed-trades-seconds: 3600
  # Fetch ingame mail of an authenticated nation and post it to a channel
  # Set the values to 0 to disable
  # Copy the default block for multiple users
  # The tasks will fail if a user is not authenticated (user/pass)
  mail:
    default:
      nation-id: 255385
      fetch-interval-seconds: 300
      channel-id: 987071057854865418
  # If any turn related tasks are run (default: true)
  enable-turn-tasks: true
  # Runs the post update raid alerts (default: 1 second)
  # Deprecated, use the beigeAlert stuff instead, which sets reminders before turn change
  raid-update-processor-seconds: 600
  # Runs the pre update beige reminders (default: 61 seconds)
  beige-reminder-seconds: 60
  # Alerts for MMR changes (default 127 minutes)
  officer-mmr-alert-seconds: 1800
  # What range of top alliances to check the MMR of (default: 80)
  officer-mmr-alert-top-x: 100
  # Fetches general nation information (default: 60)
  active-nation-updater-seconds: 900
  # Fetches wars and then attacks (default 3 minutes)
  war-attack-seconds: 600
  # Fetches baseball games (default 2 hours)
  baseball-seconds: 14400
  # Fetches the bounties (default 1 hour)
  bounty-update-seconds: 1800
  war-attacks-escalation-alerts: true
  # Fetches spies in the background via the api (default: false)
  # If disabled, spies will be fetched when needed
  # *Requires setting the `trackspies` coalition in the root server
  fetch-spies-background-api: false
  # Fetches spies in the background via webscrape (default: false)
  # If disabled, spies will be fetched when needed
  # *Requires setting the `trackspies` coalition in the root server
  fetch-spies-background-scrape: false
  # If network UIDs are fetched (for multi checking) (default: false)
  fetch-uuid: false

discord:
  channel:
    # The channel id to receive admin alerts in (set to 0 to disable)
    admin-alerts: 987069386365997098
    # The channel id to receive error alerts in (set to 0 to disable)
    errors: 987069386365997098
  intents:
    guild-members: true
    guild-presences: true
    guild-messages: true
    guild-message-reactions: true
    direct-messages: true
    emoji: true
  cache:
    member-overrides: true
    online-status: true
    emote: true
  command:
    # The prefix used for legacy commands (single character)
    legacy-command-prefix: "%"
    # The prefix used for v2 commands (single character)
    command-prefix: ";"
  # User ids of people who can `!register` other nations
  # Only give this to trusted people, since it can be abused
  register-anyone: []
  # User ids of people who can `!register` other nations who are applicants in their alliance
  # Less abusable version of the above, since applicants aren't typically important that impersonation would be too damagingaaaaaaaaaaa
  register-applicants: []

web:
  # The url/op/hostname for the web interface
  redirect: "https://locutus.link"
  # File location of the ssl certificate
  #  - You can get a free certificate from e.g. https://zerossl.com/ or https://letsencrypt.org/
  #  - Set to empty string to not use an ssl certificate
  cert-path: "C:/Certbot/live/locutus.link/"
  # The password or passphrase for the certificate
  # Leave blank if there is none
  cert-password: ''
  # Port used for HTTP. Set to 0 to disable
  port-http: 80
  # Port used for secure HTTPS. Set to 0 to disable
  port-https: 443
  # If set to true, web content is not compressed/minified
  development: false

# Prevent users, nations, alliances from using the bot
moderation:
  banned-nations: []
  banned-users: []
  banned-guilds: []
  banned-alliances: []

update-processor:
  threshold-bank-sub-alert: 600
  threshold-all-bank-alert: 1800

legacy-settings:
  # Can bypass the normal transfer cap
  whitelisted-bank-users: []

# Proxy settings (Not implemented, work in progress)
#  - Locutus commands can perform alliance administration actions
#  - A proxy can aid multiple alliances performing actions concurrently
proxy:
  user: "username@example.com"
  password: "12345678"
  # The available hosts to use
  # multiple hosts will be distributed amongst the clients used
  hosts: 
  - "region.example.com"
  port: 1080

database:
  # TODO: MySQL support is not fully implemented. Request this to be finished if important
  mysql:
    # Should MySQL be used?
    use: false
    host: "localhost"
    port: 3306
    user: "root"
    password: "password"
  sqlite:
    # Should SQLite be used?
    use: true
    # The directory to store the database in
    directory: "database"
