package link.locutus.discord.web.commands.binding.protos;

import org.checkerframework.checker.nullness.qual.Nullable;
import java.util.List;
import java.util.Map;
import java.util.Set;
import link.locutus.discord.apiv1.enums.BuildingType;
import link.locutus.discord.apiv1.enums.ResourceType;
import link.locutus.discord.apiv1.enums.Continent;
import link.locutus.discord.apiv1.enums.MilitaryUnit;
public class Building_Web {
    @Nullable public double getRequiredCitizens;
    @Nullable public int getBaseProduction;
    @Nullable public String nameSnakeCase;
    @Nullable public double getUpkeep;
    @Nullable public BuildingType getType;
    @Nullable public int countCanBuild;
    @Nullable public Map<ResourceType, Double> getCostMap;
    @Nullable public ResourceType getResourceProduced;
    @Nullable public double getResource;
    @Nullable public double getResourceValue;
    @Nullable public double getMarketCost;
    @Nullable public Set<Continent> getContinents;
    @Nullable public int getTotal;
    @Nullable public int getInfraBase;
    @Nullable public int getUnitDailyBuy;
    @Nullable public int getInfraMax;
    @Nullable public double cost;
    @Nullable public int getCommerce;
    @Nullable public double getNMarketCost;
    @Nullable public double getPowerResourceConsumed;
    @Nullable public int getCap;
    @Nullable public MilitaryUnit getMilitaryUnit;
    @Nullable public ResourceType getPowerResource;
    @Nullable public int getPollution;
    @Nullable public int getAverage;
    @Nullable public String name;
    @Nullable public int getUnitCap;
    @Nullable public Map<ResourceType, Double> getUpkeepMap;
    @Nullable public int ordinal;
    @Nullable public boolean canBuild;
    @Nullable public List<ResourceType> getResourceTypesConsumed;
}