package link.locutus.discord.web.commands.binding.protos;

import org.checkerframework.checker.nullness.qual.Nullable;
import java.util.List;
import java.util.Map;
import java.util.Set;
import link.locutus.discord.apiv1.enums.NationColor;
import link.locutus.discord.apiv1.enums.ResourceType;
import link.locutus.discord.apiv1.enums.TreatyType;
public class DBAlliance_Web {
    @Nullable public double getCities;
    @Nullable public int getNumTreasures;
    @Nullable public NationColor getColor;
    @Nullable public String getDiscord_link;
    @Nullable public double getRevenueConverted;
    @Nullable public String getFlag;
    @Nullable public double getResource;
    @Nullable public String getUrl;
    @Nullable public int getRank;
    @Nullable public double getResourceValue;
    @Nullable public int getAlliance_id;
    @Nullable public double getTreasureBonus;
    @Nullable public int getTreatyOrdinal;
    @Nullable public String getAcronym;
    @Nullable public double exponentialCityStrength;
    @Nullable public double getTotal;
    @Nullable public long getDateCreated;
    @Nullable public double getScore;
    @Nullable public String getForum_link;
    @Nullable public Map<ResourceType, Double> getRevenue;
    @Nullable public String getWiki_link;
    @Nullable public int getId;
    @Nullable public Set<DBAlliance_Web> getTreatiedAllies;
    @Nullable public int getNumWarsSince;
    @Nullable public String getName;
    @Nullable public double getAverage;
    @Nullable public int countNations;
    @Nullable public double getAveragePer;
    @Nullable public TreatyType getTreatyType;
    @Nullable public boolean hasDefensiveTreaty;
}