package link.locutus.discord.util.battle;

public enum BlitzWarningCode {
    BELOW_WAR_RANGE,
    ABOVE_WAR_RANGE,
    UPDECLARE_TOO_STRONG,
    DEFENDER_SLOTTED,
    DEFENDER_SPY_SLOTTED,
    ATTACKER_INACTIVE,
    ATTACKER_VM,
    DEFENDER_INACTIVE,
    DEFENDER_VM,
    ATTACKER_AT_MAX_OFFENSIVES,
    UNKNOWN_NATION,
    DUPLICATE_NATION,
    NATION_ON_BOTH_SIDES,
    ACTIVE_PAIR_CONFLICT,
    BEIGE_DEFENDER,
    TREATY_BLOCKED,
    MANUAL_DECLARATION_REJECTED,
    MANUAL_DECLARATION_FORCED,
    OVERRIDE_INVALID,
    ALLIANCE_MISMATCH,
    TARGET_NOT_ENEMY,
    DUPLICATE_SHEET_COLUMN
}
