package link.locutus.discord.commands.manager.v2.impl.pw.ranking;

public enum RankingKind {
    ALLIANCE_METRIC,
    ALLIANCE_ATTRIBUTE,
    ALLIANCE_METRIC_DELTA,
    ALLIANCE_LOOT,
    BASEBALL_GAMES,
    BASEBALL_CHALLENGE_GAMES,
    BASEBALL_EARNINGS,
    BASEBALL_CHALLENGE_EARNINGS,
    INCENTIVE,
    POTENTIAL_OFFSHORES,
    PROLIFIC_OFFSHORES,
    NATION_ATTRIBUTE,
    PRODUCTION,
    RECRUITMENT,
    TRADE_FLOW,
    TRADE_PROFIT,
    WAR_STATUS,
    WAR_COST,
    WAR_COUNT,
    ATTACK_TYPE
}
