/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package link.locutus.discord.web.commands.binding.value_types;
@org.apache.avro.specific.AvroGenerated
public enum CacheType implements org.apache.avro.generic.GenericEnumSymbol<CacheType> {
  None, Cookie, LocalStorage, SessionStorage  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CacheType\",\"namespace\":\"link.locutus.discord.web.commands.binding.value_types\",\"symbols\":[\"None\",\"Cookie\",\"LocalStorage\",\"SessionStorage\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
