/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package link.locutus.discord.web.commands.binding.value_types;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WebAudit extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6071061609112677784L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WebAudit\",\"namespace\":\"link.locutus.discord.web.commands.binding.value_types\",\"fields\":[{\"name\":\"audit\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"severity\",\"type\":\"int\"},{\"name\":\"value\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WebAudit> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WebAudit> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WebAudit> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WebAudit> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WebAudit> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WebAudit to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WebAudit from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WebAudit instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WebAudit fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence audit;
  private java.lang.CharSequence description;
  private int severity;
  private java.lang.CharSequence value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WebAudit() {}

  /**
   * All-args constructor.
   * @param audit The new value for audit
   * @param description The new value for description
   * @param severity The new value for severity
   * @param value The new value for value
   */
  public WebAudit(java.lang.CharSequence audit, java.lang.CharSequence description, java.lang.Integer severity, java.lang.CharSequence value) {
    this.audit = audit;
    this.description = description;
    this.severity = severity;
    this.value = value;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return audit;
    case 1: return description;
    case 2: return severity;
    case 3: return value;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: audit = (java.lang.CharSequence)value$; break;
    case 1: description = (java.lang.CharSequence)value$; break;
    case 2: severity = (java.lang.Integer)value$; break;
    case 3: value = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'audit' field.
   * @return The value of the 'audit' field.
   */
  public java.lang.CharSequence getAudit() {
    return audit;
  }


  /**
   * Sets the value of the 'audit' field.
   * @param value the value to set.
   */
  public void setAudit(java.lang.CharSequence value) {
    this.audit = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'severity' field.
   * @return The value of the 'severity' field.
   */
  public int getSeverity() {
    return severity;
  }


  /**
   * Sets the value of the 'severity' field.
   * @param value the value to set.
   */
  public void setSeverity(int value) {
    this.severity = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /**
   * Creates a new WebAudit RecordBuilder.
   * @return A new WebAudit RecordBuilder
   */
  public static link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder newBuilder() {
    return new link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder();
  }

  /**
   * Creates a new WebAudit RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WebAudit RecordBuilder
   */
  public static link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder newBuilder(link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder other) {
    if (other == null) {
      return new link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder();
    } else {
      return new link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder(other);
    }
  }

  /**
   * Creates a new WebAudit RecordBuilder by copying an existing WebAudit instance.
   * @param other The existing instance to copy.
   * @return A new WebAudit RecordBuilder
   */
  public static link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder newBuilder(link.locutus.discord.web.commands.binding.value_types.WebAudit other) {
    if (other == null) {
      return new link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder();
    } else {
      return new link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder(other);
    }
  }

  /**
   * RecordBuilder for WebAudit instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WebAudit>
    implements org.apache.avro.data.RecordBuilder<WebAudit> {

    private java.lang.CharSequence audit;
    private java.lang.CharSequence description;
    private int severity;
    private java.lang.CharSequence value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.audit)) {
        this.audit = data().deepCopy(fields()[0].schema(), other.audit);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.severity)) {
        this.severity = data().deepCopy(fields()[2].schema(), other.severity);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing WebAudit instance
     * @param other The existing instance to copy.
     */
    private Builder(link.locutus.discord.web.commands.binding.value_types.WebAudit other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.audit)) {
        this.audit = data().deepCopy(fields()[0].schema(), other.audit);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.severity)) {
        this.severity = data().deepCopy(fields()[2].schema(), other.severity);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'audit' field.
      * @return The value.
      */
    public java.lang.CharSequence getAudit() {
      return audit;
    }


    /**
      * Sets the value of the 'audit' field.
      * @param value The value of 'audit'.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder setAudit(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.audit = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'audit' field has been set.
      * @return True if the 'audit' field has been set, false otherwise.
      */
    public boolean hasAudit() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'audit' field.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder clearAudit() {
      audit = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'severity' field.
      * @return The value.
      */
    public int getSeverity() {
      return severity;
    }


    /**
      * Sets the value of the 'severity' field.
      * @param value The value of 'severity'.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder setSeverity(int value) {
      validate(fields()[2], value);
      this.severity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'severity' field has been set.
      * @return True if the 'severity' field has been set, false otherwise.
      */
    public boolean hasSeverity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'severity' field.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder clearSeverity() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.CharSequence getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.value = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebAudit.Builder clearValue() {
      value = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WebAudit build() {
      try {
        WebAudit record = new WebAudit();
        record.audit = fieldSetFlags()[0] ? this.audit : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.severity = fieldSetFlags()[2] ? this.severity : (java.lang.Integer) defaultValue(fields()[2]);
        record.value = fieldSetFlags()[3] ? this.value : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WebAudit>
    WRITER$ = (org.apache.avro.io.DatumWriter<WebAudit>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WebAudit>
    READER$ = (org.apache.avro.io.DatumReader<WebAudit>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.audit);

    out.writeString(this.description);

    out.writeInt(this.severity);

    out.writeString(this.value);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.audit = in.readString(this.audit instanceof Utf8 ? (Utf8)this.audit : null);

      this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);

      this.severity = in.readInt();

      this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.audit = in.readString(this.audit instanceof Utf8 ? (Utf8)this.audit : null);
          break;

        case 1:
          this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          break;

        case 2:
          this.severity = in.readInt();
          break;

        case 3:
          this.value = in.readString(this.value instanceof Utf8 ? (Utf8)this.value : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










