/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package link.locutus.discord.web.commands.binding.value_types;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WebAudits extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8571260557609218211L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WebAudits\",\"namespace\":\"link.locutus.discord.web.commands.binding.value_types\",\"fields\":[{\"name\":\"values\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"WebAudit\",\"fields\":[{\"name\":\"audit\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"severity\",\"type\":\"int\"},{\"name\":\"value\",\"type\":\"string\"}]},\"java-class\":\"java.util.List\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WebAudits> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WebAudits> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WebAudits> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WebAudits> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WebAudits> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WebAudits to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WebAudits from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WebAudits instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WebAudits fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit> values;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WebAudits() {}

  /**
   * All-args constructor.
   * @param values The new value for values
   */
  public WebAudits(java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit> values) {
    this.values = values;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return values;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: values = (java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'values' field.
   * @return The value of the 'values' field.
   */
  public java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit> getValues() {
    return values;
  }


  /**
   * Sets the value of the 'values' field.
   * @param value the value to set.
   */
  public void setValues(java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit> value) {
    this.values = value;
  }

  /**
   * Creates a new WebAudits RecordBuilder.
   * @return A new WebAudits RecordBuilder
   */
  public static link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder newBuilder() {
    return new link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder();
  }

  /**
   * Creates a new WebAudits RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WebAudits RecordBuilder
   */
  public static link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder newBuilder(link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder other) {
    if (other == null) {
      return new link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder();
    } else {
      return new link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder(other);
    }
  }

  /**
   * Creates a new WebAudits RecordBuilder by copying an existing WebAudits instance.
   * @param other The existing instance to copy.
   * @return A new WebAudits RecordBuilder
   */
  public static link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder newBuilder(link.locutus.discord.web.commands.binding.value_types.WebAudits other) {
    if (other == null) {
      return new link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder();
    } else {
      return new link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder(other);
    }
  }

  /**
   * RecordBuilder for WebAudits instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WebAudits>
    implements org.apache.avro.data.RecordBuilder<WebAudits> {

    private java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit> values;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.values)) {
        this.values = data().deepCopy(fields()[0].schema(), other.values);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing WebAudits instance
     * @param other The existing instance to copy.
     */
    private Builder(link.locutus.discord.web.commands.binding.value_types.WebAudits other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.values)) {
        this.values = data().deepCopy(fields()[0].schema(), other.values);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'values' field.
      * @return The value.
      */
    public java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit> getValues() {
      return values;
    }


    /**
      * Sets the value of the 'values' field.
      * @param value The value of 'values'.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder setValues(java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit> value) {
      validate(fields()[0], value);
      this.values = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'values' field has been set.
      * @return True if the 'values' field has been set, false otherwise.
      */
    public boolean hasValues() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'values' field.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebAudits.Builder clearValues() {
      values = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WebAudits build() {
      try {
        WebAudits record = new WebAudits();
        record.values = fieldSetFlags()[0] ? this.values : (java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WebAudits>
    WRITER$ = (org.apache.avro.io.DatumWriter<WebAudits>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WebAudits>
    READER$ = (org.apache.avro.io.DatumReader<WebAudits>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.values.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (link.locutus.discord.web.commands.binding.value_types.WebAudit e0: this.values) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit> a0 = this.values;
      if (a0 == null) {
        a0 = new SpecificData.Array<link.locutus.discord.web.commands.binding.value_types.WebAudit>((int)size0, SCHEMA$.getField("values").schema());
        this.values = a0;
      } else a0.clear();
      SpecificData.Array<link.locutus.discord.web.commands.binding.value_types.WebAudit> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<link.locutus.discord.web.commands.binding.value_types.WebAudit>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          link.locutus.discord.web.commands.binding.value_types.WebAudit e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new link.locutus.discord.web.commands.binding.value_types.WebAudit();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<link.locutus.discord.web.commands.binding.value_types.WebAudit> a0 = this.values;
          if (a0 == null) {
            a0 = new SpecificData.Array<link.locutus.discord.web.commands.binding.value_types.WebAudit>((int)size0, SCHEMA$.getField("values").schema());
            this.values = a0;
          } else a0.clear();
          SpecificData.Array<link.locutus.discord.web.commands.binding.value_types.WebAudit> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<link.locutus.discord.web.commands.binding.value_types.WebAudit>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              link.locutus.discord.web.commands.binding.value_types.WebAudit e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new link.locutus.discord.web.commands.binding.value_types.WebAudit();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










