/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package link.locutus.discord.web.commands.binding.value_types;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WebBankAccess extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3278287046558244568L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WebBankAccess\",\"namespace\":\"link.locutus.discord.web.commands.binding.value_types\",\"fields\":[{\"name\":\"access\",\"type\":{\"type\":\"map\",\"values\":\"int\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WebBankAccess> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WebBankAccess> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WebBankAccess> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WebBankAccess> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WebBankAccess> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WebBankAccess to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WebBankAccess from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WebBankAccess instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WebBankAccess fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.Map<java.lang.CharSequence,java.lang.Integer> access;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WebBankAccess() {}

  /**
   * All-args constructor.
   * @param access The new value for access
   */
  public WebBankAccess(java.util.Map<java.lang.CharSequence,java.lang.Integer> access) {
    this.access = access;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return access;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: access = (java.util.Map<java.lang.CharSequence,java.lang.Integer>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'access' field.
   * @return The value of the 'access' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.Integer> getAccess() {
    return access;
  }


  /**
   * Sets the value of the 'access' field.
   * @param value the value to set.
   */
  public void setAccess(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
    this.access = value;
  }

  /**
   * Creates a new WebBankAccess RecordBuilder.
   * @return A new WebBankAccess RecordBuilder
   */
  public static link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder newBuilder() {
    return new link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder();
  }

  /**
   * Creates a new WebBankAccess RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WebBankAccess RecordBuilder
   */
  public static link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder newBuilder(link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder other) {
    if (other == null) {
      return new link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder();
    } else {
      return new link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder(other);
    }
  }

  /**
   * Creates a new WebBankAccess RecordBuilder by copying an existing WebBankAccess instance.
   * @param other The existing instance to copy.
   * @return A new WebBankAccess RecordBuilder
   */
  public static link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder newBuilder(link.locutus.discord.web.commands.binding.value_types.WebBankAccess other) {
    if (other == null) {
      return new link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder();
    } else {
      return new link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder(other);
    }
  }

  /**
   * RecordBuilder for WebBankAccess instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WebBankAccess>
    implements org.apache.avro.data.RecordBuilder<WebBankAccess> {

    private java.util.Map<java.lang.CharSequence,java.lang.Integer> access;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.access)) {
        this.access = data().deepCopy(fields()[0].schema(), other.access);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing WebBankAccess instance
     * @param other The existing instance to copy.
     */
    private Builder(link.locutus.discord.web.commands.binding.value_types.WebBankAccess other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.access)) {
        this.access = data().deepCopy(fields()[0].schema(), other.access);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'access' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.Integer> getAccess() {
      return access;
    }


    /**
      * Sets the value of the 'access' field.
      * @param value The value of 'access'.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder setAccess(java.util.Map<java.lang.CharSequence,java.lang.Integer> value) {
      validate(fields()[0], value);
      this.access = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'access' field has been set.
      * @return True if the 'access' field has been set, false otherwise.
      */
    public boolean hasAccess() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'access' field.
      * @return This builder.
      */
    public link.locutus.discord.web.commands.binding.value_types.WebBankAccess.Builder clearAccess() {
      access = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WebBankAccess build() {
      try {
        WebBankAccess record = new WebBankAccess();
        record.access = fieldSetFlags()[0] ? this.access : (java.util.Map<java.lang.CharSequence,java.lang.Integer>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WebBankAccess>
    WRITER$ = (org.apache.avro.io.DatumWriter<WebBankAccess>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WebBankAccess>
    READER$ = (org.apache.avro.io.DatumReader<WebBankAccess>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.access.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, java.lang.Integer> e0: this.access.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.Integer v0 = e0.getValue();
      out.writeInt(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,java.lang.Integer> m0 = this.access; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.Integer>((int)(size0 * 4)/3 + 1);
        this.access = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence k0 = null;
          k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
          java.lang.Integer v0 = null;
          v0 = in.readInt();
          m0.put(k0, v0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,java.lang.Integer> m0 = this.access; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.Integer>((int)(size0 * 4)/3 + 1);
            this.access = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence k0 = null;
              k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
              java.lang.Integer v0 = null;
              v0 = in.readInt();
              m0.put(k0, v0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










