/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package link.locutus.discord.apiv1.enums;
@org.apache.avro.specific.AvroGenerated
public enum NationColor implements org.apache.avro.generic.GenericEnumSymbol<NationColor> {
  AQUA, BEIGE, BLACK, BLUE, BROWN, GRAY, GREEN, LIME, MAROON, OLIVE, ORANGE, PINK, PURPLE, RED, WHITE, YELLOW  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NationColor\",\"namespace\":\"link.locutus.discord.apiv1.enums\",\"symbols\":[\"AQUA\",\"BEIGE\",\"BLACK\",\"BLUE\",\"BROWN\",\"GRAY\",\"GREEN\",\"LIME\",\"MAROON\",\"OLIVE\",\"ORANGE\",\"PINK\",\"PURPLE\",\"RED\",\"WHITE\",\"YELLOW\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
